"""исправлены имена атрибутов user->cafe, booking->table

Revision ID: 7cf170b19154
Revises: 018b0680ce9c
Create Date: 2026-04-03 17:48:06.727134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf170b19154'
down_revision: Union[str, Sequence[str], None] = '018b0680ce9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings_tables',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'table_id')
    )
    op.drop_table('bookings_tabels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings_tabels',
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'table_id')
    )
    op.drop_table('bookings_tables')
    # ### end Alembic commands ###
